### PR TITLE
Clarifies that there is commands needing to be run

### PR DESCRIPTION
**Pull request by Andrew-J-Larson**
Especially with the first part, since at first I thought it was all just one command for the install process.

### CODE REVIEW

**Comment by Botspot** [comment]
I did consider putting the $ character in front of each command, but I decided against it because it would be harder to copy-n-paste both lines at once into the terminal.
Also, I've seen several beginners get confused what the `$` is there for. (they tried to run `$` in the terminal and got back "bash: $: command not found")

**Comment by Botspot** [comment]
OK, I've edited README.md to separate out all 3 commands. I think it's the best compromise available to minimize user confusion.
Let me know what you think of it.

**Comment by Andrew-J-Larson** [comment]
Works for me! Though, you could just combine the first command with the install command like so:

`git clone https://github.com/Botspot/Windows-10 && /home/pi/Windows-10/install`

**Comment by Botspot** [comment]
That && is also a good idea, but I figured some users may want to look around in the folder before they install it. Hence why I'm going to keep the commands separate.
Edit: Also many, many users will want to re-run the install command, but not re-download it. If both commands were chained up, they couldn't do that.

**Comment by Andrew-J-Larson** [comment]
Fair point.

**Pull request closed without merging**
